# Generated by Django 3.2.20 on 2023-08-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=60)),
                ('Position', models.CharField(default=1, max_length=100)),
                ('CompanyName', models.CharField(default=1, max_length=60)),
                ('Place', models.CharField(default=1, max_length=120)),
                ('Post', models.CharField(default=1, max_length=100)),
                ('Pin', models.CharField(default=1, max_length=60)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupNumber', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=100)),
                ('TopicName', models.CharField(max_length=100)),
                ('Status', models.CharField(default='Pending', max_length=100)),
                ('GrpBatchid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.batch')),
                ('Grp_External_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.externalguide')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=60)),
                ('UserType', models.CharField(default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.CharField(default=1, max_length=100)),
                ('Gender', models.CharField(max_length=60)),
                ('Education', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.BigIntegerField()),
                ('Login', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.login')),
                ('std_batchid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Progress1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prgrs', models.CharField(default=1, max_length=120)),
                ('PDate', models.CharField(default=1, max_length=100)),
                ('PGroupid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.group')),
            ],
        ),
        migrations.CreateModel(
            name='InternGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=60)),
                ('Position', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.BigIntegerField(default=1)),
                ('Login', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.login')),
            ],
        ),
        migrations.CreateModel(
            name='GroupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prgrs', models.CharField(default=1, max_length=120)),
                ('PDate', models.CharField(default=1, max_length=100)),
                ('PGroupid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groupid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.group')),
                ('Studid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.students')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='Grp_Internal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.internguide'),
        ),
        migrations.AddField(
            model_name='externalguide',
            name='Login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.login'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='')),
                ('AGroupid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.group')),
            ],
        ),
    ]
