# Generated by Django 3.2.20 on 2023-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completemyproject', '0002_delete_progress1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Subject',
            new_name='Subject1',
        ),
        migrations.AddField(
            model_name='schedule',
            name='Subject2',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
