# Generated by Django 3.2.20 on 2023-08-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('completemyproject', '0003_auto_20230812_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fromid', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='Subject1',
            new_name='Subject',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Subject2',
        ),
        migrations.AddField(
            model_name='schedule',
            name='Batchid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='completemyproject.batch'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(default=1, max_length=60),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Date',
            field=models.DateField(max_length=100),
        ),
    ]
