# Generated by Django 3.2.20 on 2023-09-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completemyproject', '0007_group_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Login',
            new_name='Login1',
        ),
    ]
