# Generated by Django 3.2.20 on 2023-09-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completemyproject', '0008_rename_login_group_login1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Login1',
            new_name='Login',
        ),
    ]
