# Generated by Django 3.2.20 on 2023-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completemyproject', '0009_rename_login1_group_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Remarks',
            field=models.CharField(default=1, max_length=400),
        ),
    ]
