# Generated by Django 3.2.20 on 2023-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completemyproject', '0010_attendance_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprogress',
            name='GrRemarks',
            field=models.CharField(default=1, max_length=400),
        ),
        migrations.AlterField(
            model_name='groupprogress',
            name='Prgrs',
            field=models.FileField(default=1, max_length=120, upload_to=''),
        ),
    ]
